#!/usr/bin/env python2.7
# encoding: utf-8
'''
finance.tbimport -- import Trybooking "Account Transactions" CSV report file(s)

Note: basic program outline generated by PyDev (Eclipse plugin) via New->PyDev
      Module command and the "CLI (optparse)" Module template

@author:     Murray Jensen
@copyright:  2016 Murray Jensen. All rights reserved.
@license:    GPLv3
@contact:    mjj@jensen-williams.id.au
'''
from __future__ import print_function

from argparse import ArgumentParser, RawDescriptionHelpFormatter
from logging import getLogger, basicConfig
import os
import sys
from traceback import format_exc

from sbcilib.financedb import SbciFinanceDB
from sbcilib.trybooking import TBXactReadCSV


__all__ = []
__version__ = 0.1
__date__ = '2016-04-29'
__updated__ = '$Date$'.split()[0]

_logger = getLogger(__file__)

DEBUG_RUN = 1
TEST_RUN = 0
PROFILE_RUN = 0


def main(argv=None):
    '''Command line options.'''

    basicConfig()

    if argv is not None:
        sys.argv.extend(argv)

    program_name = os.path.basename(sys.argv[0])
    program_version = "v%s" % __version__
    program_build_date = str(__updated__)
    program_version_message = '%%(prog)s %s (%s)' % (
        program_version, program_build_date)
    program_doclines = __import__('__main__').__doc__.split("\n")
    program_shortdesc = program_doclines[1]
    program_longdesc = program_doclines[3:]  # @UnusedVariable
    program_license = '''%s

  Created by Murray Jensen on %s.
  Copyright 2016 Murray Jensen. All rights reserved.

  Licensed under the GNU GENERAL PUBLIC LICENSE
                       Version 3, 29 June 2007

USAGE
''' % (program_shortdesc, str(__date__))

    try:
        # Setup argument parser
        parser = ArgumentParser(description=program_license,
                                formatter_class=RawDescriptionHelpFormatter)
        parser.add_argument(
            "-v",
            "--verbose",
            dest="verbose",
            action="count",
            help="set verbosity level [default: %(default)s]")
        parser.add_argument(
            '-V',
            '--version',
            action='version',
            version=program_version_message)
        parser.add_argument(
            "-n",
            "--dryrun",
            dest="dryrun",
            action="store_true",
            help="do not change the database [default: %(default)s]")
        parser.add_argument('csvlist', nargs='+')
        # Process arguments
        args = parser.parse_args()
    except KeyboardInterrupt:
        # handle keyboard interrupt
        return os.EX_OK
    except Exception as e:
        if DEBUG_RUN or TEST_RUN:
            raise(e)
        indent = len(program_name) * " "
        sys.stderr.write(program_name + ": " + repr(e) + "\n")
        sys.stderr.write(indent + "  for help use --help")
        return os.EX_USAGE

    if args.verbose > 0:
        print("Verbose mode on (level = {})".format(args.verbose))
        print("CSV file list = {}".format(args.csvlist))
        if args.dryrun:
            print('Dry run! Will not modify database.')

    try:
        db = SbciFinanceDB(args.verbose)

        csvrecords = []
        for csvfile in args.csvlist:
            csvrecords.extend(TBXactReadCSV(csvfile, args.verbose))

        if args.verbose > 0:
            print('All CSV files read - storing data ...')

        for csvrecord in sorted(csvrecords, key=lambda r: r.date):

            maybe_dups = db.trybooking_query.filter(
                db.Trybooking.xact == csvrecord.xact.csv_value,
                db.Trybooking.booking_id == csvrecord.booking_id,
                db.Trybooking.description == csvrecord.description,
                db.Trybooking.customer == csvrecord.customer,
                db.Trybooking.debit == csvrecord.debit,
                db.Trybooking.credit == csvrecord.credit
            ).all()

            found_dup = False
            prev_dup = None

            for maybe_dup in maybe_dups:
                if maybe_dup.date.date() == csvrecord.date.date():
                    if args.verbose > 1:
                        print('DUPLICATE!! {}'.format(csvrecord))

                    if found_dup:
                        raise RuntimeError(
                            'matched more than one! {},{},{}'.format(
                                db.trybooking_format(prev_dup),
                                db.trybooking_format(maybe_dup),
                                csvrecord
                            )
                        )

                    if maybe_dup.date != csvrecord.date:
                        if args.dryrun:
                            if args.verbose > 0:
                                print('(dryrun) Need to update date: {} => {}'
                                      .format(maybe_dup.date, csvrecord.date))
                        else:
                            if args.verbose > 0:
                                print('Updated date: {} => {}'
                                      .format(maybe_dup.date, csvrecord.date))
                            maybe_dup.date = csvrecord.date
                            db.dbsession.commit()

                    found_dup = True
                    prev_dup = maybe_dup

            if not found_dup:
                if args.dryrun:
                    if args.verbose > 0:
                        print('(dryrun) NEW RECORD: {}'.format(csvrecord))
                else:
                    if args.verbose > 0:
                        print('NEW RECORD: {}'.format(csvrecord), end='')
                    dbrec = db.Trybooking(
                        date=csvrecord.date,
                        type=csvrecord.xact.csv_value,
                        description=csvrecord.description.encode('utf-8'),
                        debit=csvrecord.debit,
                        credit=csvrecord.credit
                    )
                    db.dbsession.add(dbrec)
                    db.dbsession.flush()
                    if args.verbose > 0:
                        print(' => ID{}'.format(dbrec.id))

        return os.EX_OK

    except KeyboardInterrupt:
        # handle keyboard interrupt
        return os.EX_OK

    except Exception as e:
        if DEBUG_RUN or TEST_RUN:
            print(format_exc())
            raise(e)
        indent = len(program_name) * " "
        sys.stderr.write(program_name + ": " + repr(e) + "\n")
        sys.stderr.write(indent + "  for help use --help\n")
        return os.EX_USAGE


if __name__ == "__main__":
    if TEST_RUN:
        import doctest
        doctest.testmod()
    if PROFILE_RUN:
        import cProfile
        import pstats
        profile_filename = 'finance.tbimport_profile.txt'
        cProfile.run('main()', profile_filename)
        statsfile = open("profile_stats.txt", "wb")
        p = pstats.Stats(profile_filename, stream=statsfile)
        stats = p.strip_dirs().sort_stats('cumulative')
        stats.print_stats()
        statsfile.close()
        sys.exit(os.EX_OK)
    sys.exit(main())
