#!/usr/bin/env python2.7
# encoding: utf-8
'''
checkstg -- check that info in SportsTG matches the database

checkstg is a program that reads a SportsTG CSV file and checks that it matches
the database.
--
Note: basic program structure based on code generated by PyDev (Eclipse plugin)
      via New->PyDev Module command and the "CLI (argparse)" Module template

@author:     Murray Jensen

@copyright:  2018 Murray Jensen. All rights reserved.

@license:    Apache License 2.0

@contact:    mjj@jensen-williams.id.au

@deffield    updated: $Date$
@deffield    updated by: $Author$
@deffield    last revision: $Revision$
'''
from __future__ import print_function

from argparse import ArgumentParser, RawDescriptionHelpFormatter
from logging import getLogger, basicConfig
import os
import re
import sys

from sbcilib.sportstg import STGMembersCSVRead
from sbcilib.teamsdb import SbciTeamsDB, TeamRole


__all__ = []
__version__ = 0.1
__date__ = '2018-07-29'
__updated__ = re.sub(r'^\$Date: (\S+) .*$', r'\1', '$Date$')

_logger = getLogger(__file__)

DEBUG_RUN = 0
TEST_RUN = 0
PROFILE_RUN = 0


def main(argv=None):
    '''Command line options.'''

    basicConfig()

    if argv is not None:
        sys.argv.extend(argv)

    program_name = os.path.basename(sys.argv[0])
    program_version = "v%s" % __version__
    program_build_date = str(__updated__)
    program_version_message = '%%(prog)s %s (%s)' % (
        program_version, program_build_date)
    program_doclines = __import__('__main__').__doc__.split("\n")
    program_shortdesc = program_doclines[1]
    program_longdesc = program_doclines[3:]  # @UnusedVariable
    program_license = '''%s

  Created by Murray Jensen on %s.
  Copyright 2018 Murray Jensen. All rights reserved.

  Licensed under the GNU GENERAL PUBLIC LICENSE
                       Version 3, 29 June 2007

USAGE
''' % (program_shortdesc, str(__date__))

    try:
        # Setup argument parser
        parser = ArgumentParser(description=program_license,
                                formatter_class=RawDescriptionHelpFormatter)
        parser.add_argument(
            "-v",
            "--verbose",
            dest="verbose",
            action="count",
            help="set verbosity level [default: %(default)s]")
        parser.add_argument(
            '-V',
            '--version',
            action='version',
            version=program_version_message)
        # Process arguments
        args = parser.parse_args()
    except KeyboardInterrupt:
        # handle keyboard interrupt
        return os.EX_OK
    except Exception as e:
        if DEBUG_RUN or TEST_RUN:
            raise(e)
        indent = len(program_name) * " "
        sys.stderr.write(program_name + ": " + repr(e) + "\n")
        sys.stderr.write(indent + "  for help use --help\n")
        return os.EX_USAGE

    verbose = args.verbose
    if verbose > 0:
        print("Verbose mode on (level = {}).".format(verbose))
        print('Current Working Directory = {}'.format(os.getcwd()))

    try:
        db = SbciTeamsDB(verbose)

        member_records = STGMembersCSVRead('reportdata-members.csv', verbose)

        for team in sorted(db.teams_query.all(), key=lambda x: x.team_name):
            if team.active != 'true':
                continue

            competition = db.competitions_query.get(team.competition_id)
            competition_longname = db.competition_longname(competition)

            coach = db.people_query.get(team.coach_id)
            asst_coach = db.people_query.get(team.asst_coach_id)
            team_manager = db.people_query.get(team.team_manager_id)

            if verbose:
                print('{}, {}:'.format(team.team_name, competition_longname))

            team_roles = [
                (TeamRole.COACH, coach),
                (TeamRole.TEAM_MANAGER, team_manager),
                (TeamRole.ASSISTANT_COACH, asst_coach),
            ]

            for role, person in team_roles:
                if person.id == 0:
                    continue

                member_matches = []
                for record in member_records:
                    name = record.first_name + ' ' + record.family_name
                    if name.lower() == person.name.lower():
                        member_matches.append(record)

                nmatches = len(member_matches)
                if nmatches == 0:
                    raise RuntimeError('{} has no SportsTG record!'
                                       .format(person.name))
                elif nmatches > 1:
                    raise RuntimeError('{} matches more than 1 SportsTG record!'
                                       .format(person.name))

                member_record = member_matches[0]
                need_update = False
                if verbose > 0:
                    result = '{}: {}'.format(role.alt_value, person.name)

                if person.email != member_record.email:
                    if verbose > 0:
                        result += ' +EMAIL'
                    need_update = True

                if person.mobile != member_record.mobile:
                    if verbose > 0:
                        result += ' +MOBILE'
                    need_update = True

                if not db.person_is_under18(person):

                    if person.wwc_number != member_record.wwc_check_number:
                        if verbose > 0:
                            result += ' +WWCNUM'
                        need_update = True

                    if (person.wwc_expiry.date() !=
                            member_record.wwc_check_expiry):
                        if verbose > 0:
                            result += ' +WWCEXP'
                        need_update = True

                if person.dob.date() != member_record.date_of_birth:
                    if verbose > 0:
                        result += ' +DOB'
                    need_update = True

                need_role_update = False
                if role == TeamRole.COACH:
                    need_role_update = (member_record.season_coach != 'Yes')
                if role == TeamRole.TEAM_MANAGER:
                    need_role_update = (member_record.season_misc != 'Yes')
                if need_role_update:
                    if verbose > 0:
                        result += ' +{}'.format(role.name)
                    need_update = True

                if verbose > 0:
                    if need_update:
                        print('**', end='')
                    print('\t{}.'.format(result))
                elif need_update:
                    print('\t{}: {} NEEDS UPDATE!'
                          .format(role.alt_value, person.name))

        return os.EX_OK

    except KeyboardInterrupt:
        # handle keyboard interrupt
        return os.EX_OK

    except Exception as e:
        if DEBUG_RUN or TEST_RUN:
            raise(e)
        _logger.exception('Exception')
        indent = len(program_name) * " "
        sys.stderr.write(program_name + ": " + repr(e) + "\n")
        sys.stderr.write(indent + "  for help use --help\n")
        return os.EX_USAGE


if __name__ == "__main__":
    if TEST_RUN:
        import doctest
        doctest.testmod(verbose=verbose, report=True)
    if PROFILE_RUN:
        import cProfile
        import pstats
        profile_filename = 'teams.readtest_profile.txt'
        cProfile.run('main()', profile_filename)
        statsfile = open("profile_stats.txt", "wb")
        p = pstats.Stats(profile_filename, stream=statsfile)
        stats = p.strip_dirs().sort_stats('cumulative')
        stats.print_stats()
        statsfile.close()
        sys.exit(os.EX_OK)
    sys.exit(main())
