#!/usr/bin/env python2.7
# encoding: utf-8
'''
teams.readtest -- test reading of teams sqlite3 database

Note: basic program outline generated by PyDev (Eclipse plugin) via New->PyDev
      Module command and the "CLI (optparse)" Module template

@author:     Murray Jensen
@copyright:  2016 Murray Jensen. All rights reserved.
@license:    GPLv3
@contact:    mjj@jensen-williams.id.au
'''
from argparse import ArgumentParser, RawDescriptionHelpFormatter
from logging import getLogger, basicConfig
import os
import sys

from sbcilib.teamsdb import SbciTeamsDB


__all__ = []
__version__ = 0.1
__date__ = '2016-04-29'
__updated__ = '$Date$'.split()[0]

_logger = getLogger(__file__)

DEBUG_RUN = 0
TEST_RUN = 0
PROFILE_RUN = 0


def main(argv=None):
    '''Command line options.'''

    basicConfig()

    if argv is not None:
        sys.argv.extend(argv)

    program_name = os.path.basename(sys.argv[0])
    program_version = "v%s" % __version__
    program_build_date = str(__updated__)
    program_version_message = '%%(prog)s %s (%s)' % (
        program_version, program_build_date)
    program_doclines = __import__('__main__').__doc__.split("\n")
    program_shortdesc = program_doclines[1]
    program_longdesc = program_doclines[3:]  # @UnusedVariable
    program_license = '''%s

  Created by Murray Jensen on %s.
  Copyright 2016 Murray Jensen. All rights reserved.

  Licensed under the GNU GENERAL PUBLIC LICENSE
                       Version 3, 29 June 2007

USAGE
''' % (program_shortdesc, str(__date__))

    try:
        # Setup argument parser
        parser = ArgumentParser(description=program_license,
                                formatter_class=RawDescriptionHelpFormatter)
        parser.add_argument(
            "-v",
            "--verbose",
            dest="verbose",
            action="count",
            help="set verbosity level [default: %(default)s]")
        parser.add_argument(
            '-V',
            '--version',
            action='version',
            version=program_version_message)
        # Process arguments
        args = parser.parse_args()
    except KeyboardInterrupt:
        # handle keyboard interrupt
        return os.EX_OK
    except Exception as e:
        if DEBUG_RUN or TEST_RUN:
            raise(e)
        indent = len(program_name) * " "
        sys.stderr.write(program_name + ": " + repr(e) + "\n")
        sys.stderr.write(indent + "  for help use --help")
        return os.EX_USAGE

    verbose = args.verbose
    if verbose > 0:
        print("Verbose mode on")

    try:
        db = SbciTeamsDB(verbose)

        try:
            for team in db.teams_query.all():
                if not team.active:
                    continue

                team_manager = db.people_query.get(team.team_manager_id)
                coach = db.people_query.get(team.coach_id)
                asst_coach = db.people_query.get(team.asst_coach_id)

                if verbose:
                    competition = db.competitions_query.get(team.competition_id)
                    print('{}, {}: coach {}, asst_coach {}, team manager {}'
                          .format(team.team_name,
                                  db.competition_shortname(competition),
                                  coach.name, asst_coach.name,
                                  team_manager.name))

                r, m, e = db.person_check_wwc(coach, verbose)
                if not r:
                    print('WWC check failed: {}'.format(m))

                r, m, e = db.person_check_wwc(asst_coach, verbose)
                if not r:
                    print('WWC check failed: {}'.format(m))

                r, m, e = db.person_check_wwc(team_manager, verbose)
                if not r:
                    print('WWC check failed: {}'.format(m))

        except BaseException:
            _logger.exception('Exception')
            return os.EX_OSERR

        return os.EX_OK

    except KeyboardInterrupt:
        # handle keyboard interrupt
        return os.EX_OK

    except Exception as e:
        if DEBUG_RUN or TEST_RUN:
            raise(e)
        _logger.exception('Exception')
        indent = len(program_name) * " "
        sys.stderr.write(program_name + ": " + repr(e) + "\n")
        sys.stderr.write(indent + "  for help use --help")
        return os.EX_USAGE


if __name__ == "__main__":
    if TEST_RUN:
        import doctest
        doctest.testmod()
    if PROFILE_RUN:
        import cProfile
        import pstats
        profile_filename = 'teams.readtest_profile.txt'
        cProfile.run('main()', profile_filename)
        statsfile = open("profile_stats.txt", "wb")
        p = pstats.Stats(profile_filename, stream=statsfile)
        stats = p.strip_dirs().sort_stats('cumulative')
        stats.print_stats()
        statsfile.close()
        sys.exit(os.EX_OK)
    sys.exit(main())
