#!/usr/bin/env python2.7
# encoding: utf-8
'''
process -- process CSV report from Trybooking and produce order sheet

process CSV report from Trybooking and produce order sheet
--
Note: basic program outline generated by PyDev (Eclipse plugin) via New->PyDev
      Module command and the "CLI (argparse)" Module template

@version:    0.1
@created:    2016-05-23
@author:     Murray Jensen
@copyright:  2016 Murray Jensen. All rights reserved.
@license:    Apache License 2.0
@contact:    mjj@jensen-williams.id.au
$Date$
$Author$
$Revision$
'''
import csv
import json
import os
import sys

from sbcilib.utils import SbciMain


class Main(SbciMain):

    def define_args(self):
        super(Main, self).define_args()
        self.parser.add_argument('csvlist', nargs='+')

    def main(self):
        try:
            # with open('config.json', 'r') as fd:
            #     config = json.load(fd)  # @UnusedVariable

            for csvfile in self.args.csvlist:
                print 'csvfile: "%s"' % csvfile
                with open(csvfile) as fd:
                    reader = csv.DictReader(fd)
                    for d in reader:
                        for k in d.keys():
                            print '\t"%s"' % k
                        break
        except KeyboardInterrupt:
            print('\nGot Interrupted!')
            return os.EX_SOFTWARE


def main():
    '''function suitable for running via setuptools entry point'''
    return Main.setuptools_entry()


if __name__ == '__main__':
    sys.exit(main())
